spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?createDatabaseIfNotExist=true

    username: root
    password:
  jpa:
    generate-ddl: true
    show-sql: true
hibernate:
      ddl-auto: update

server:
  port: 8081
#   sql: